modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="brushwoods"
version="${file.jarVersion}"
displayName="TheBrushwoods"

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="TheBrushwoods.png" #optional

# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
authors="Jwx" #optional

# The description text for the mod (multi line!) (#mandatory) - update this J
description='''
The Brushwoods Mod
'''

[[dependencies.brushwoods]]
   modId="forge"
   mandatory=true
versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.brushwoods]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
